import org.junit.Test;

import ngapp.example.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'QuanLe' at '5/28/16 5:11 PM' with Gradle 2.9
 *
 * @author QuanLe, @date 5/28/16 5:11 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
