package ngapp.example;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'QuanLe' at '5/28/16 5:11 PM' with Gradle 2.9
 *
 * @author QuanLe, @date 5/28/16 5:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
